### ISSUE TITLE
Com.Artifex.Mupdfdemo.ReaderView.Adapter' is marked as an override but no suitable property found

### ISSUE THREAD

**Issue by dharmik** [asimmon/MuPDF-for-Xamarin-Android#1]
/../MuPDF-for-Xamarin-Android/src/Askaiser.Android.MuPDF/obj/Debug/generated/src/Com.Artifex.Mupdfdemo.ReaderView.cs(58,58): Error CS0115: `Com.Artifex.Mupdfdemo.ReaderView.Adapter' is marked as an override but no suitable property found to override (CS0115) (Askaiser.Android.MuPDF)

**Comment by asimmon** [comment]
Hi @dharmik, thanks for reporting this bug. I have just updated the MuPDF library to the latest version (1.9a). I have also modified `Metadata.xml` and `PartialClasses.cs` to solve this bug (and others). Please look the comments in these files if you want more information.

**Important**: The .NET namespace `Com.Artifex.Mupdfdemo` has been renamed to `Artifex.MuPdf`.
